services:
  postgres:
    image: postgres:latest
    container_name: ""
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: ""
    volumes:
      - ./data:/var/lib/postgresql/data
